# Basic Memory DSH integration package

install:
    npm ci --ignore-scripts

check-types:
    npm run check-types

build:
    npm run build

test:
    npm test

pack:
    npm run pack:dry-run

release-check:
    npm run release:check

check: install check-types test build pack
